name: 'Linux CMake Build'
description: 'Run CMake build and test steps'

inputs:
  compiler:
    required: true
    description: 'Compiler to use (gcc or clang)'
  build-type:
    required: true
    description: 'Build type (editor or game)'
  configuration:
    required: true
    description: 'Build configuration (debug, release, or profile)'

runs:
  using: "composite"
  steps:
    - name: Get number of CPU cores
      shell: bash
      id: cpu-cores
      run: echo "count=$(nproc)" >> $GITHUB_OUTPUT

    - name: Build and test ${{ inputs.build-type }} in ${{ inputs.configuration }} mode
      uses: lukka/run-cmake@v10
      env:
        CMAKE_BUILD_PARALLEL_LEVEL: ${{ steps.cpu-cores.outputs.count }}
      with:
        configurePreset: linux-${{ inputs.compiler }}${{ inputs.build-type == 'editor' && '-editor' || '' }}
        buildPreset: linux-${{ inputs.compiler }}-${{ inputs.configuration }}${{ inputs.build-type == 'editor' && '-editor' || '' }}
        testPreset: test-linux-${{ inputs.compiler }}-${{ inputs.configuration }}${{ inputs.build-type == 'editor' && '-editor' || '' }}

    - name: Record build timing
      shell: bash
      run: |
        echo "$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_STEP_SUMMARY
        echo "Build completed for ${{ inputs.compiler }}-${{ inputs.build-type }}-${{ inputs.configuration }}" >> $GITHUB_STEP_SUMMARY
